# -*- coding: utf-8 -*-
"""
Builder for sections 39 to 45 cards with 100% natural, authentic furigana Japanese examples.
Zero mechanical repeated phrases.
"""

# Section 39: ない-form 1 (26 verbs)
SEC_39_RAW = [
    ("起きない（おきない）", "to wake up / to get up", "일어나다", "起床／起來", "2グループ (一段)",
     "<ruby>明日<rt>あした</rt></ruby>は<ruby>休<rt>やす</rt></ruby>みだから、<ruby>朝<rt>あさ</rt></ruby><ruby>早<rt>はや</rt></ruby>く起きない。",
     "Tomorrow is a holiday, so I won't wake up early in the morning.",
     "내일은 쉬는 날이라서 아침 일찍 일어나지 않아요.",
     "明天放假，所以早上不起得早。"),
    ("勉強をしない（べんきょうをしない）", "to study", "공부하다", "讀書／學習", "3グループ (サ変)",
     "<ruby>今日<rt>きょう</rt></ruby>はテストが<ruby>終<rt>お</rt></ruby>わったので、もう<ruby>勉強<rt>べんきょう</rt></ruby>をしない。",
     "The exam is over today, so I won't study anymore.",
     "오늘은 시험이 끝나서 이제 공부를 안 해요.",
     "今天考試結束了，所以不再讀書了。"),
    ("行かない（いかない）", "to go", "가다", "去", "1グループ (五段)",
     "<ruby>熱<rt>ねつ</rt></ruby>があるので、<ruby>今日<rt>きょう</rt></ruby>のパーティーには行かない。",
     "I have a fever, so I won't go to today's party.",
     "열이 있어서 오늘 파티에는 안 가요.",
     "我發燒了，所以不去今天的派對。"),
    ("帰らない（かえらない）", "to return / to go home", "돌아가다 / 집에 가다", "回去／回家", "1グループ (五段)",
     "<ruby>終電<rt>しゅうでん</rt></ruby>に<ruby>間<rt>ま</rt></ruby>に<ruby>合<rt>あ</rt></ruby>わないので、<ruby>今夜<rt>こんや</rt></ruby>は<ruby>家<rt>いえ</rt></ruby>に帰らない。",
     "I missed the last train, so I won't return home tonight.",
     "막차를 놓쳐서 오늘 밤은 집에 돌아가지 않아요.",
     "趕不上末班車，所以今晚不回家。"),
    ("来ない（こない）", "to come", "오다", "來", "3グループ (カ変)",
     "<ruby>雨<rt>あめ</rt></ruby>が<ruby>降<rt>ふ</rt></ruby>っているから、<ruby>田中<rt>たなか</rt></ruby>さんは来ないかもしれない。",
     "Because it's raining, Tanaka might not come.",
     "비가 내리고 있어서 다나카 씨는 안 올지도 몰라요.",
     "因為下雨，田中先生可能不會來。"),
    ("食べない（たべない）", "to eat", "먹다", "吃", "2グループ (一段)",
     "ダイエット<ruby>中<rt>ちゅう</rt></ruby>なので、<ruby>夜<rt>よる</rt></ruby>は<ruby>甘<rt>あま</rt></ruby>いお<ruby>菓子<rt>かし</rt></ruby>を食べない。",
     "I am on a diet, so I don't eat sweet snacks at night.",
     "다이어트 중이라서 밤에는 단 과자를 안 먹어요.",
     "我在節食，所以晚上不吃甜食。"),
    ("飲まない（のまない）", "to drink", "마시다", "喝", "1グループ (五段)",
     "<ruby>車<rt>くるま</rt></ruby>を<ruby>運転<rt>うんてん</rt></ruby>するから、お<ruby>酒<rt>さけ</rt></ruby>は飲まない。",
     "I will drive a car, so I don't drink alcohol.",
     "운전을 해야 해서 술은 안 마셔요.",
     "我要開車，所以不喝酒。"),
    ("寝ない（ねない）", "to sleep / to go to bed", "자다", "睡覺", "2グループ (一段)",
     "<ruby>面白<rt>おもしろ</rt></ruby>いドラマを<ruby>見<rt>み</rt></ruby>ていて、<ruby>夜遅<rt>よるおそ</rt></ruby>くまで寝ない。",
     "I am watching an interesting drama and don't go to bed until late.",
     "재미있는 드라마를 보느라 늦은 밤까지 안 자요.",
     "看著有趣的電視劇，很晚都還沒睡。"),
    ("見ない（みない）", "to look / to watch / to see", "보다", "看", "2グループ (一段)",
     "<ruby>忙<rt>いそが</rt></ruby>しくて、<ruby>最近<rt>さいきん</rt></ruby>はテレビをまったく見ない。",
     "I am busy, so lately I don't watch TV at all.",
     "바빠서 요즘은 텔레비전을 전혀 안 봐요.",
     "最近很忙，完全不看電視。"),
    ("聞かない（きかない）—質問・情報", "to ask / to hear", "묻다 / 듣다", "問／詢問", "1グループ (五段)",
     "<ruby>彼<rt>かれ</rt></ruby>のプライベートのことは、あえて聞かないようにしている。",
     "I make a point of not asking about his private life.",
     "그의 개인적인 일은 굳이 묻지 않으려고 해요.",
     "他的私事，我特意不去多問。"),
    ("聴かない（きかない）—音楽など", "to listen", "듣다", "聽", "1グループ (五段)",
     "<ruby>普段<rt>ふだん</rt></ruby>はロックをあまり聴かない。",
     "I usually don't listen to rock music much.",
     "평소에는 록 음악을 별로 듣지 않아요.",
     "平時不太聽搖滾樂。"),
    ("読まない（よまない）", "to read", "읽다", "讀／看（書）", "1グループ (五段)",
     "<ruby>電子書籍<rt>でんししょせき</rt></ruby>ばかりで、<ruby>紙<rt>かみ</rt></ruby>の<ruby>本<rt>ほん</rt></ruby>はほとんど読まない。",
     "I only read e-books and hardly read paper books.",
     "전자책만 읽고 종이책은 거의 안 읽어요.",
     "我只看電子書，幾乎不讀紙本書。"),
    ("話さない（はなさない）", "to speak / to talk", "말하다 / 이야기하다", "說話／講話", "1グループ (五段)",
     "<ruby>図書館<rt>としょかん</rt></ruby>の<ruby>中<rt>なか</rt></ruby>では<ruby>大<rt>おお</rt></ruby>きな<ruby>声<rt>こえ</rt></ruby>で話さないでください。",
     "Please don't speak in a loud voice inside the library.",
     "도서관 안에서는 큰 소리로 이야기하지 마세요.",
     "在圖書館裡請不要大聲說話。"),
    ("会わない（あわない）", "to meet / to see someone", "만나다", "見面／碰面", "1グループ (五段)",
     "<ruby>卒業<rt>そつぎょう</rt></ruby>してから、<ruby>昔<rt>むかし</rt></ruby>の<ruby>友達<rt>ともだち</rt></ruby>とあまり会わない。",
     "Since graduating, I don't see my old friends very often.",
     "졸업한 뒤로 옛 친구들과 잘 안 만나요.",
     "畢業之後，很少和老朋友見面。"),
    ("買わない（かわない）", "to buy / to purchase", "사다", "買", "1グループ (五段)",
     "<ruby>高<rt>たか</rt></ruby>すぎるから、このコートは買わない。",
     "It's too expensive, so I won't buy this coat.",
     "너무 비싸서 이 코트는 안 사요.",
     "太貴了，所以我不會買這件大衣。"),
    ("しない", "to do", "하다", "做", "3グループ (サ変)",
     "<ruby>今日<rt>きょう</rt></ruby>は<ruby>何<rt>なに</rt></ruby>もしないで、のんびりすごしたい。",
     "I don't want to do anything today, just relax.",
     "오늘은 아무것도 안 하고 푹 쉬고 싶어요.",
     "今天什麼都不想做，只想好好放鬆。"),
    ("始まらない（はじまらない）", "to begin / to start (intransitive)", "시작되다", "開始", "1グループ (五段)",
     "<ruby>先生<rt>せんせい</rt></ruby>がまだ<ruby>来<rt>こ</rt></ruby>ないので、<ruby>授業<rt>じゅぎょう</rt></ruby>が始まらない。",
     "The teacher hasn't come yet, so the lesson doesn't start.",
     "선생님이 아직 안 오셔서 수업이 시작되지 않아요.",
     "老師還沒來，所以課程還沒開始。"),
    ("終わらない（おわらない）", "to end / to finish (intransitive)", "끝나다", "結束／完了", "1グループ (五段)",
     "<ruby>仕事<rt>しごと</rt></ruby>がなかなか終わらなくて、<ruby>困<rt>こま</rt></ruby>っています。",
     "My work just doesn't finish, and I'm having trouble.",
     "일이 좀처럼 끝나지 않아서 곤란해요.",
     "工作一直做不完，真讓人困擾。"),
    ("働かない（はたらかない）", "to work", "일하다", "工作／返工", "1グループ (五段)",
     "<ruby>日曜日<rt>にちようび</rt></ruby>は<ruby>会社<rt>かいしゃ</rt></ruby>で働かない。",
     "I do not work at the company on Sundays.",
     "일요일에는 회사에서 일하지 않아요.",
     "星期天不在公司上班。"),
    ("驚かない（おどろかない）", "to be surprised", "깜짝 놀라다", "嚇一跳", "1グループ (五段)",
     "<ruby>前<rt>まえ</rt></ruby>から<ruby>知<rt>し</rt></ruby>っていたので、そのニュースを<ruby>聞<rt>き</rt></ruby>いても驚かない。",
     "I knew it beforehand, so even hearing the news I am not surprised.",
     "전부터 알고 있었기 때문에 그 뉴스를 들어도 놀라지 않아요.",
     "因為之前就知道了，所以聽到那個消息也不吃驚。"),
    ("忘れない（わすれない）", "to forget", "잊어버리다", "忘記／唔記得", "2グループ (一段)",
     "<ruby>日本<rt>にほん</rt></ruby>で<ruby>過<rt>す</rt></ruby>ごした<ruby>楽<rt>たの</rt></ruby>しい<ruby>思<rt>おも</rt></ruby>い<ruby>出<rt>で</rt></ruby>を、ずっと忘れない。",
     "I will never forget the pleasant memories spent in Japan.",
     "일본에서 보낸 즐거운 추억을 계속 잊지 않아요.",
     "永遠不會忘記在日本度過的美好回憶。"),
    ("覚えない（おぼえない）", "to memorize", "외우다・기억하다", "記住／記得", "2グループ (一段)",
     "<ruby>使<rt>つか</rt></ruby>わない<ruby>単語<rt>たんご</rt></ruby>は、なかなか<ruby>頭<rt>あたま</rt></ruby>に覚えない。",
     "Words I don't use are hard to memorize in my head.",
     "안 쓰는 단어는 머릿속에 잘 외워지지 않아요.",
     "不常用的單字，很難記在腦子裡。"),
    ("乗らない（のらない）", "to get on", "타다", "搭・騎・坐", "1グループ (五段)",
     "<ruby>道<rt>みち</rt></ruby>が<ruby>混<rt>こ</rt></ruby>んでいるので、バスには乗らないで<ruby>歩<rt>ある</rt></ruby>きます。",
     "The roads are congested, so I won't ride the bus and will walk.",
     "길이 막혀서 버스를 안 타고 걸어가요.",
     "路上塞車，所以不坐公車改為步行。"),
    ("降りない（おりない）", "to get off", "내리다", "下車／落車", "2グループ (一段)",
     "この<ruby>駅<rt>えき</rt></ruby>では降りないで、<ruby>次<rt>つぎ</rt></ruby>の<ruby>駅<rt>えき</rt></ruby>まで<ruby>行<rt>い</rt></ruby>きます。",
     "I won't get off at this station, but continue to the next one.",
     "이 역에서는 안 내리고 다음 역까지 가요.",
     "不在這一站下車，坐到下一站。"),
    ("休まない（やすまない）", "to rest", "쉬다", "休息／放假", "1グループ (五段)",
     "<ruby>彼<rt>かれ</rt></ruby>は<ruby>風邪<rt>かぜ</rt></ruby>をひいても、<ruby>学校<rt>がっこう</rt></ruby>を休まない。",
     "Even if he catches a cold, he doesn't take time off from school.",
     "그는 감기에 걸려도 학교를 쉬지 않아요.",
     "即使感冒了，他也不請假缺課。"),
    ("遊ばない（あそばない）", "to hang out / to play", "놀다", "玩／去玩", "1グループ (五段)",
     "<ruby>試験<rt>しけん</rt></ruby>の<ruby>前<rt>まえ</rt></ruby>は、<ruby>友達<rt>ともだち</rt></ruby>と<ruby>外<rt>そと</rt></ruby>で遊ばない。",
     "Before the exam, I don't hang out outside with friends.",
     "시험 전에는 친구들과 밖에서 안 놀아요.",
     "考試前不和朋友在外面玩。")
]

# Section 40: ない-form 2 (25 verbs)
SEC_40_RAW = [
    ("出ない（でない）", "to leave / to go out", "나가다", "出去／出來", "2グループ (一段)",
     "<ruby>寒<rt>さむ</rt></ruby>いので、<ruby>今日<rt>きょう</rt></ruby>は<ruby>部屋<rt>へや</rt></ruby>から一歩も出ない。",
     "It's cold, so today I won't step out of the room at all.",
     "날씨가 추워서 오늘은 방에서 한 발짝도 안 나가요.",
     "天氣很冷，今天一步也不踏出房間。"),
    ("入らない（はいらない）", "to enter", "들어가다", "進去／進入", "1グループ (五段)",
     "<ruby>関係者<rt>かんけいしゃ</rt></ruby><ruby>以外<rt>いがい</rt></ruby>は、この<ruby>部屋<rt>へや</rt></ruby>に入らないでください。",
     "Except for authorized personnel, please do not enter this room.",
     "관계자 외에는 이 방에 들어가지 마세요.",
     "除相關人員外，請勿進入此房間。"),
    ("着かない（つかない）", "to arrive", "도착하다", "到達／到了", "1グループ (五段)",
     "<ruby>電車<rt>でんしゃ</rt></ruby>が<ruby>遅<rt>おく</rt></ruby>れていて、<ruby>約束<rt>やくそく</rt></ruby>の<ruby>時間<rt>じかん</rt></ruby>に着かないかもしれない。",
     "The train is delayed, so I might not arrive at the agreed time.",
     "전철이 지연되어 약속 시간에 도착하지 못할 수도 있어요.",
     "電車延誤了，可能無法在約定時間到達。"),
    ("渡らない（わたらない）", "to cross", "건너다", "過（馬路）／渡過", "1グループ (五段)",
     "<ruby>信号<rt>しんごう</rt></ruby>が<ruby>赤<rt>あか</rt></ruby>のときは、<ruby>横断歩道<rt>おうだんほどう</rt></ruby>を渡らない。",
     "When the traffic light is red, do not cross the crosswalk.",
     "신호등이 빨간 불일 때는 횡단보도를 건너지 않아요.",
     "紅燈的時候，不要過斑馬線。"),
    ("歩かない（あるかない）", "to walk", "걷다", "走路／步行", "1グループ (五段)",
     "<ruby>足<rt>あし</rt></ruby>が<ruby>痛<rt>いた</rt></ruby>いので、<ruby>今日<rt>きょう</rt></ruby>はあまり歩かない。",
     "My foot hurts, so I won't walk much today.",
     "다리가 아파서 오늘은 많이 걷지 않아요.",
     "腳很痛，所以今天不太走路。"),
    ("走らない（はしらない）", "to run", "달리다", "跑步／跑", "1グループ (五段)",
     "<ruby>廊下<rt>ろうか</rt></ruby>は<ruby>危<rt>あぶ</rt></ruby>ないですから、走らないでください。",
     "The hallway is dangerous, so please do not run.",
     "복도는 위험하니까 달리지 마세요.",
     "走廊很危險，請不要奔跑。"),
    ("起こさない（おこさない）", "to wake someone up", "깨우다", "叫醒（某人）", "1グループ (五段)",
     "<ruby>赤<rt>あか</rt></ruby>ちゃんがぐっすり<ruby>眠<rt>ねむ</rt></ruby>っているので、起こさないようにする。",
     "The baby is sleeping soundly, so I try not to wake him up.",
     "아기가 곤히 자고 있어서 깨우지 않도록 해요.",
     "寶寶睡得很香，所以我盡量不去吵醒他。"),
    ("洗わない（あらわない）", "to wash", "씻다", "洗", "1グループ (五段)",
     "このセーターはデリケートだから、<ruby>洗濯機<rt>せんたくき</rt></ruby>で洗わない。",
     "This sweater is delicate, so I don't wash it in the washing machine.",
     "이 스웨터는 섬세해서 세탁기로 빨지 않아요.",
     "這件毛衣很細緻，所以不用洗衣機洗。"),
    ("着ない（きない）", "to wear / to put on (top)", "입다", "穿（上衣）", "2グループ (一段)",
     "<ruby>暖<rt>あたた</rt></ruby>かい<ruby>春<rt>はる</rt></ruby>になったので、<ruby>厚手<rt>あつで</rt></ruby>のコートはもう着ない。",
     "Spring has warmed up, so I no longer wear heavy coats.",
     "따뜻한 봄이 되어서 두꺼운 코트는 이제 안 입어요.",
     "天氣轉暖入春了，不再穿厚重的大衣。"),
    ("脱がない（ぬがない）", "to take off (clothes)", "벗다", "脫（衣服）", "1グループ (五段)",
     "<ruby>部屋<rt>へや</rt></ruby>がまだ<ruby>肌寒<rt>はだざむ</rt></ruby>いので、カーディガンを脱がない。",
     "The room is still chilly, so I don't take off my cardigan.",
     "방이 아직 쌀쌀해서 가디건을 안 벗어요.",
     "房間裡還有點涼，所以不脫針織衫。"),
    ("開けない（あけない）", "to open", "열다", "打開", "2グループ (一段)",
     "<ruby>外<rt>そと</rt></ruby>がうるさいので、<ruby>窓<rt>まど</rt></ruby>を開けないでおく。",
     "It's noisy outside, so I keep the windows unopened.",
     "밖이 시끄러워서 창문을 열지 않고 둬요.",
     "外面很吵，所以先不開窗。"),
    ("閉めない（しめない）", "to close", "닫다", "關上／關閉", "2グループ (一段)",
     "<ruby>空気<rt>くうき</rt></ruby>を<ruby>入<rt>い</rt></ruby>れ<ruby>替<rt>か</rt></ruby>えるために、ドアを閉めない。",
     "To let fresh air circulate, I don't close the door.",
     "환기하기 위해 문을 닫지 않아요.",
     "為了通風換氣，我不關門。"),
    ("使わない（つかわない）", "to use", "사용하다", "使用／用", "1グループ (五段)",
     "<ruby>料理<rt>りょうり</rt></ruby>に<ruby>化学調味料<rt>かがくちょうみりょう</rt></ruby>を使わないようにしている。",
     "I make sure not to use chemical seasonings in cooking.",
     "요리에 화학조미료를 쓰지 않으려고 해요.",
     "做菜時盡量不使用化學調味料。"),
    ("作らない（つくらない）", "to make", "만들다", "做／製作", "1グループ (五段)",
     "<ruby>今日<rt>きょう</rt></ruby>は<ruby>疲<rt>つか</rt></ruby>れたので、<ruby>晩<rt>ばん</rt></ruby>ご<ruby>飯<rt>はん</rt></ruby>を作らないで<ruby>外食<rt>がいしょく</rt></ruby>する。",
     "I'm tired today, so I won't make dinner and will eat out.",
     "오늘은 피곤해서 저녁을 안 만들고 외식해요.",
     "今天累了，不煮晚餐改在外面吃。"),
    ("切らない（きらない）", "to cut", "자르다", "切／剪", "1グループ (五段)",
     "<ruby>髪<rt>かみ</rt></ruby>を<ruby>伸<rt>の</rt></ruby>ばしたいので、しばらく切らない。",
     "I want to grow my hair long, so I won't cut it for a while.",
     "머리를 기르고 싶어서 당분간 자르지 않아요.",
     "我想留長頭髮，所以暫時不剪。"),
    ("書かない（かかない）", "to write", "쓰다", "寫", "1グループ (五段)",
     "パソコンばかりで、<ruby>手紙<rt>てがみ</rt></ruby>を手で書かないようになった。",
     "I only use computers now and have stopped writing letters by hand.",
     "컴퓨터만 쓰다 보니 편지를 손으로 쓰지 않게 되었어요.",
     "都用電腦了，變得不再親手寫信。"),
    ("答えない（こたえない）", "to answer", "대답하다", "回答", "2グループ (一段)",
     "<ruby>不審<rt>ふしん</rt></ruby>なアンケートには答えない方がいい。",
     "It's better not to answer suspicious surveys.",
     "의심스러운 설문조사에는 대답하지 않는 편이 좋아요.",
     "可疑的問卷調查最好不要回答。"),
    ("教えない（おしえない）", "to teach / to tell", "가르치다", "教／告訴", "2グループ (一段)",
     "サプライズだから、<ruby>秘密<rt>ひみつ</rt></ruby>の<ruby>場所<rt>ばしょ</rt></ruby>はまだ教えない。",
     "It's a surprise, so I won't tell you the secret place yet.",
     "깜짝 이벤트라서 비밀 장소는 아직 안 가르쳐 줘요.",
     "因為是驚喜，所以秘密地點暫時還不告訴你。"),
    ("聞こえない（きこえない）", "to be able to hear / can hear", "들리다", "聽得到／聽得見", "2グループ (一段)",
     "<ruby>声<rt>こえ</rt></ruby>が<ruby>小<rt>ちい</rt></ruby>さくて、よく聞こえない。",
     "Your voice is small, so I can't hear well.",
     "목소리가 작아서 잘 안 들려요.",
     "聲音太小了，聽不太清楚。"),
    ("見えない（みえない）", "to be able to see / can see", "보이다", "看得到／看得見", "2グループ (一段)",
     "<ruby>霧<rt>きり</rt></ruby>が<ruby>濃<rt>こ</rt></ruby>くて、<ruby>前<rt>まえ</rt></ruby>がよく見えない。",
     "The fog is thick, so I cannot see ahead clearly.",
     "안개가 짙어서 앞이 잘 안 보여요.",
     "霧很濃，前方看不太清楚。"),
    ("待たない（またない）", "to wait", "기다리다", "等／等待", "1グループ (五段)",
     "<ruby>時間<rt>じかん</rt></ruby>がないので、これ<ruby>以上<rt>いじょう</rt></ruby>は待たないで行きます。",
     "I don't have time, so I won't wait any longer and will go.",
     "시간이 없어서 더 이상 안 기다리고 가겠어요.",
     "沒有時間了，不能再等下去了，我先走。"),
    ("思わない（おもわない）", "to think / to feel", "생각하다", "覺得／認為", "1グループ (五段)",
     "<ruby>彼<rt>かれ</rt></ruby>の<ruby>意見<rt>いけん</rt></ruby>が<ruby>正<rt>ただ</rt></ruby>しいとは、どうしても思わない。",
     "I really don't think his opinion is correct.",
     "그의 의견이 옳다고는 아무래도 생각하지 않아요.",
     "無論如何我都覺得他的意見並不正確。"),
    ("知らない（しらない）", "to know / to find out", "알다", "知道", "1グループ (五段)",
     "その<ruby>事件<rt>じけん</rt></ruby>の詳しいことは、<ruby>何<rt>なに</rt></ruby>も知らない。",
     "I don't know anything about the details of that incident.",
     "그 사건의 자세한 내용은 아무것도 몰라요.",
     "關於那起事件的詳細情形，我什麼都不知道。"),
    ("わからない", "to understand", "이해하다", "明白／懂", "1グループ (五段)",
     "いくら<ruby>考<rt>かんが</rt></ruby>えても、この<ruby>問題<rt>もんだい</rt></ruby>の<ruby>答<rt>こた</rt></ruby>えがわからない。",
     "No matter how much I think, I don't understand the answer to this question.",
     "아무리 생각해도 이 문제의 답을 모르겠어요.",
     "怎麼想都不明白這道題目的答案。"),
    ("できない", "to be able to / can", "할 수 있다", "會／可以／能", "3グループ (サ変可能)",
     "<ruby>怪我<rt>けが</rt></ruby>をしているので、<ruby>今日<rt>きょう</rt></ruby>は激しいスポーツができない。",
     "Because I am injured, I cannot do strenuous sports today.",
     "부상을 입어서 오늘은 격렬한 운동을 못 해요.",
     "因為受傷了，今天無法做激烈的運動。")
]

# Section 41: ない-form 3 (18 verbs)
SEC_41_RAW = [
    ("泳がない（およがない）", "to swim", "수영하다", "游泳／游水", "1グループ (五段)",
     "<ruby>水<rt>みず</rt></ruby>がまだ<ruby>冷<rt>つめ</rt></ruby>たいので、プールで泳がない。",
     "The water is still cold, so I don't swim in the pool.",
     "물이 아직 차가워서 수영장에서 수영하지 않아요.",
     "水還很涼，所以不在游泳池游泳。"),
    ("疲れない（つかれない）", "to get tired", "피곤하다／지치다", "疲累／攰／累", "2グループ (一段)",
     "このクッションはとても<ruby>楽<rt>らく</rt></ruby>で、<ruby>長<rt>なが</rt></ruby>く<ruby>座<rt>すわ</rt></ruby>っても疲れない。",
     "This cushion is very comfortable and I don't get tired even sitting long.",
     "이 쿠션은 아주 편해서 오래 앉아 있어도 피곤하지 않아요.",
     "這個坐墊很舒服，坐久了也不覺得累。"),
    ("出掛けない（でかけない）", "to go out", "외출하다", "出門", "2グループ (一段)",
     "<ruby>台風<rt>たいふう</rt></ruby>が<ruby>近<rt>ちか</rt></ruby>づいているので、<ruby>今日<rt>きょう</rt></ruby>は外に出掛けない。",
     "A typhoon is approaching, so I won't go out today.",
     "태풍이 다가오고 있어서 오늘은 외출하지 않아요.",
     "颱風正在接近，所以今天不出門。"),
    ("つけない", "to turn on", "켜다", "開（電器・燈）", "2グループ (一段)",
     "<ruby>節電<rt>せつでん</rt></ruby>のために、<ruby>昼間<rt>ひるま</rt></ruby>は<ruby>電気<rt>でんき</rt></ruby>をつけない。",
     "To save electricity, I don't turn on lights in the daytime.",
     "절전을 위해 낮에는 불을 켜지 않아요.",
     "為了省電，白天不開燈。"),
    ("消さない（けさない）", "to turn off", "끄다", "關（電器・燈）", "1グループ (五段)",
     "<ruby>暗<rt>くら</rt></ruby>いのが<ruby>怖<rt>こわ</rt></ruby>いので、<ruby>豆電球<rt>まめでんきゅう</rt></ruby>を消さないで<ruby>寝<rt>ね</rt></ruby>る。",
     "I am afraid of darkness, so I sleep without turning off the nightlight.",
     "어두운 게 무서워서 미등을 끄지 않고 자요.",
     "因為害怕黑暗，所以不關夜燈睡覺。"),
    ("急がない（いそがない）", "to hurry", "서두르다", "趕快／快點", "1グループ (五段)",
     "<ruby>十分<rt>じゅうぶん</rt></ruby>に<ruby>時間<rt>じかん</rt></ruby>があるから、急がないでゆっくり<ruby>歩<rt>ある</rt></ruby>こう。",
     "We have plenty of time, so let's not hurry and walk slowly.",
     "시간이 충분하니까 서두르지 말고 천천히 걷자.",
     "時間很充裕，不著急，慢慢走吧。"),
    ("待たない（またない）", "to wait", "기다리다", "等／等待", "1グループ (五段)",
     "これ<ruby>以上<rt>いじょう</rt></ruby>は<ruby>待<rt>ま</rt></ruby>てないので、<ruby>先<rt>さき</rt></ruby>に<ruby>出発<rt>しゅっぱつ</rt></ruby>します。",
     "I cannot wait any longer, so I will depart first.",
     "더 이상은 기다리지 않고 먼저 출발할게요.",
     "不能再等了，我先出發了。"),
    ("持たない（もたない）", "to hold / to have", "들다／가지다", "拿著／拎住", "1グループ (五段)",
     "<ruby>手荷物<rt>てにもつ</rt></ruby>をたくさん持たないで、<ruby>軽<rt>かる</rt></ruby>い<ruby>服装<rt>ふくそう</rt></ruby>で<ruby>出<rt>で</rt></ruby>かける。",
     "I go out light without holding lots of baggage.",
     "짐을 많이 들지 않고 가벼운 차림으로 외출해요.",
     "不帶太多行李，輕裝出門。"),
    ("取らない（とらない）", "to take / to get", "가져오다／집다", "拿／攞", "1グループ (五段)",
     "<ruby>人<rt>ひと</rt></ruby>のものを<ruby>勝手<rt>かって</rt></ruby>に取らないでください。",
     "Please do not take other people's belongings without permission.",
     "남의 물건을 마음대로 집어 가지 마세요.",
     "請不要擅自拿別人的東西。"),
    ("手伝わない（てつだわない）", "to help (with a task)", "도와주다／거들다", "幫忙／幫手", "1グループ (五段)",
     "<ruby>自分<rt>じぶん</rt></ruby>の<ruby>力<rt>ちから</rt></ruby>でやりたいそうなので、あえて手伝わない。",
     "He wants to do it on his own, so I intentionally don't help.",
     "혼자 힘으로 하고 싶어 해서 굳이 도와주지 않아요.",
     "聽說他想靠自己的力量完成，所以我特意不去幫忙。"),
    ("助けない（たすけない）", "to help / to save", "돕다／구하다", "幫助／救", "2グループ (一段)",
     "<ruby>悪事<rt>あくじ</rt></ruby>をはたらいた<ruby>人<rt>ひと</rt></ruby>を助けないのは<ruby>当然<rt>とうぜん</rt></ruby>だ。",
     "It is natural not to help someone who committed wrongdoings.",
     "나쁜 짓을 저지른 사람을 돕지 않는 것은 당연해요.",
     "不救助做壞事的人是理所當然的。"),
    ("話さない（はなさない）", "to talk / to speak", "이야기하다／말하다", "說話／講嘢", "1グループ (五段)",
     "<ruby>会議<rt>かいぎ</rt></ruby><ruby>中<rt>ちゅう</rt></ruby>に<ruby>隣<rt>となり</rt></ruby>の<ruby>人<rt>ひと</rt></ruby>と<ruby>無駄話<rt>むだばなし</rt></ruby>を話さない。",
     "I don't chat with the person next to me during the meeting.",
     "회의 중에 옆 사람과 쓸데없는 이야기를 하지 않아요.",
     "開會時不和身旁的人閒聊。"),
    ("呼ばない（よばない）", "to call", "부르다", "叫／呼叫", "1グループ (五段)",
     "<ruby>近所迷惑<rt>きんじょめいわく</rt></ruby>になるので、<ruby>夜遅<rt>よるおそ</rt></ruby>くに<ruby>大声<rt>おおごえ</rt></ruby>で呼ばないで。",
     "It bothers the neighbors, so please don't shout to call out late at night.",
     "이웃에게 폐가 되니 밤늦게 큰 소리로 부르지 마세요.",
     "會打擾鄰居，深夜請不要大聲呼叫。"),
    ("見せない（みせない）", "to show", "보여주다", "給...看／畀...睇", "2グループ (一段)",
     "まだ<ruby>途中<rt>とちゅう</rt></ruby>だから、<ruby>描<rt>か</rt></ruby>いた<ruby>絵<rt>え</rt></ruby>を<ruby>誰<rt>だれ</rt></ruby>にも見せない。",
     "It's still work in progress, so I won't show the painting to anyone.",
     "아직 그리는 중이라 그린 그림을 누구에게도 안 보여줘요.",
     "還沒畫完，所以畫作不給任何人看。"),
    ("教えない（おしえない）", "to teach / to tell", "가르치다", "教／告訴", "2グループ (一段)",
     "パスワードは<ruby>大事<rt>だいじ</rt></ruby>な<ruby>情報<rt>じょうほう</rt></ruby>だから、<ruby>他人<rt>たにん</rt></ruby>に教えない。",
     "The password is vital information, so I don't tell it to others.",
     "비밀번호는 중요한 정보이므로 다른 사람에게 가르쳐 주지 않아요.",
     "密碼是重要資訊，所以絕不告訴別人。"),
    ("入らない（はいらない）", "to enter / to go in", "들어가다", "進去／進入", "1グループ (五段)",
     "<ruby>土足<rt>どそく</rt></ruby>でこの<ruby>畳<rt>たたみ</rt></ruby>の<ruby>部屋<rt>へや</rt></ruby>に入らないでください。",
     "Please do not enter this tatami room with shoes on.",
     "신발을 신고 이 다다미방에 들어가지 마세요.",
     "請不要穿鞋走進這間榻榻米房間。"),
    ("出ない（でない）", "to exit / to go out", "나가다／나오다", "出去", "2グループ (一段)",
     "<ruby>授業<rt>じゅぎょう</rt></ruby>が<ruby>終<rt>お</rt></ruby>わるまで、<ruby>教室<rt>きょうしつ</rt></ruby>から外に出ない。",
     "Until class ends, I will not step outside the classroom.",
     "수업이 끝날 때까지 교실 밖으로 나가지 않아요.",
     "下課之前，不走出教室。"),
    ("（雨が）降らない（ふらない）", "(rain) to fall", "비가 오다", "（下雨）", "1グループ (五段)",
     "<ruby>天気予報<rt>てんきよほう</rt></ruby>によると、<ruby>明日<rt>あした</rt></ruby>は<ruby>雨<rt>あめ</rt></ruby>が降らないそうだ。",
     "According to the weather forecast, it won't rain tomorrow.",
     "일기예보에 따르면 내일은 비가 안 온다고 해요.",
     "根據氣象預報，明天好像不會下雨。")
]

# Section 42: ない-form 4 (19 verbs)
SEC_42_RAW = [
    ("浴びない（あびない）", "to take a shower", "샤워하다", "淋浴／沖涼", "2グループ (一段)",
     "<ruby>朝<rt>あさ</rt></ruby>は<ruby>時間<rt>じかん</rt></ruby>がないので、シャワーを浴びない。",
     "I don't have time in the morning, so I don't take a shower.",
     "아침에는 시간이 없어서 샤워를 안 해요.",
     "早上沒時間，所以不沖涼。"),
    ("乗り換えない（のりかえない）", "to change trains / transfer", "환승하다", "換乘／轉車", "2グループ (一段)",
     "この<ruby>電車<rt>でんしゃ</rt></ruby>は<ruby>直通<rt>ちょくつう</rt></ruby>だから、<ruby>途中<rt>とちゅう</rt></ruby>で乗り換えないで<ruby>着<rt>つ</rt></ruby>きます。",
     "This train runs direct, so it arrives without transferring on the way.",
     "이 전철은 직통이라 도중에 환승하지 않고 도착해요.",
     "這班車是直達車，途中不用轉車就能抵達。"),
    ("入れない（いれない）", "to put in / to insert", "넣다", "放進／放入", "2グループ (一段)",
     "ブラックコーヒーが<ruby>好<rt>す</rt></ruby>きなので、<ruby>砂糖<rt>さとう</rt></ruby>を入れない。",
     "I like black coffee, so I don't put sugar in it.",
     "블랙커피를 좋아해서 설탕을 넣지 않아요.",
     "我喜歡黑咖啡，所以不加糖。"),
    ("出さない（ださない）", "to take out / to submit", "꺼내다／제출하다", "拿出來／提交", "1グループ (五段)",
     "<ruby>宿題<rt>しゅくだい</rt></ruby>を出さないと、<ruby>先生<rt>せんせい</rt></ruby>に<ruby>怒<rt>おこ</rt></ruby>られますよ。",
     "If you don't submit your homework, the teacher will get angry.",
     "숙제를 제출하지 않으면 선생님께 혼나요.",
     "如果不交作業，會被老師責備喔。"),
    ("押さない（おさない）", "to push / to press", "누르다", "按／推", "1グループ (五段)",
     "<ruby>非常<rt>ひじょう</rt></ruby>ボタンをむやみに押さないでください。",
     "Please do not press the emergency button thoughtlessly.",
     "비상 버튼을 함부로 누르지 마세요.",
     "請勿隨意按緊急按鈕。"),
    ("置かない（おかない）", "to place / to put", "놓다／두다", "放／放置", "1グループ (五段)",
     "<ruby>通路<rt>つうろ</rt></ruby>に<ruby>荷物<rt>にもつ</rt></ruby>を置かないでください。",
     "Please do not place your baggage in the aisle.",
     "통로에 짐을 놓지 마세요.",
     "請不要把行李放在走道上。"),
    ("作らない（つくらない）", "to make / to produce", "만들다", "做／製作", "1グループ (五段)",
     "<ruby>今週<rt>こんしゅう</rt></ruby>はお<ruby>弁当<rt>べんとう</rt></ruby>を作らないで、<ruby>学食<rt>がくしょく</rt></ruby>で<ruby>食<rt>た</rt></ruby>べる。",
     "This week I won't make a bento, but will eat at the cafeteria.",
     "이번 주는 도시락을 안 싸고 학생식당에서 먹어요.",
     "這星期不做便當，在學生餐廳吃。"),
    ("売らない（うらない）", "to sell", "팔다", "賣／售賣", "1グループ (五段)",
     "このアンティークの<ruby>時計<rt>とけい</rt></ruby>は<ruby>大切<rt>たいせつ</rt></ruby>なので、<ruby>誰<rt>だれ</rt></ruby>にも売らない。",
     "This antique watch is precious, so I will not sell it to anyone.",
     "이 골동품 시계는 소중해서 누구에게도 팔지 않아요.",
     "這隻古董手錶很珍貴，所以我不會賣給任何人。"),
    ("止めない（とめない）", "to stop / to park", "세우다／멈추다", "停下／停泊", "2グループ (一段)",
     "ここに<ruby>車<rt>くるま</rt></ruby>を止めないでください。<ruby>駐車禁止<rt>ちゅうしゃきんし</rt></ruby>です。",
     "Please do not park your car here. Parking is prohibited.",
     "여기에 차를 세우지 마세요. 주차 금지 구역입니다.",
     "請不要把車停在這裡，這是禁止停車區。"),
    ("座らない（すわらない）", "to sit", "앉다", "坐", "1グループ (五段)",
     "<ruby>床<rt>ゆか</rt></ruby>が<ruby>濡<rt>ぬ</rt></ruby>れているので、ここには座らない。",
     "The floor is wet, so I will not sit here.",
     "바닥이 젖어 있어서 여기에는 앉지 않아요.",
     "地板濕濕的，所以不坐在這裡。"),
    ("立たない（たたない）", "to stand up", "일어서다", "站立／起立", "1グループ (五段)",
     "<ruby>飛行機<rt>ひこうき</rt></ruby>が<ruby>動<rt>うご</rt></ruby>いている<ruby>間<rt>あいだ</rt></ruby>は、<ruby>席<rt>せき</rt></ruby>から立たないでください。",
     "While the airplane is moving, please do not stand up from your seat.",
     "비행기가 움직이는 동안에는 자리에서 일어서지 마세요.",
     "飛機滑行期間，請勿離開座位站立。"),
    ("住まない（すまない）", "to live / to reside", "살다", "居住／住", "1グループ (五段)",
     "<ruby>都会<rt>とかい</rt></ruby>は<ruby>騒<rt>ざわ</rt></ruby>がしいので、<ruby>将来<rt>しょうらい</rt></ruby>は住まないつもりです。",
     "Cities are noisy, so I plan not to live there in the future.",
     "도시는 복잡하고 시끄러워서 장래에는 살지 않을 생각이에요.",
     "大城市太吵雜，我將來不打算住在市區。"),
    ("吸わない（すわない）", "to smoke / to inhale", "피우다", "吸煙／抽煙", "1グループ (五段)",
     "<ruby>健康<rt>けんこう</rt></ruby>のために、タバコは一切吸わない。",
     "For my health, I do not smoke cigarettes at all.",
     "건강을 위해 담배는 전혀 피우지 않아요.",
     "為了健康，完全不抽菸。"),
    ("覚えない（おぼえない）", "to memorize / to remember", "외우다", "記住／記得", "2グループ (一段)",
     "<ruby>興味<rt>きょうみ</rt></ruby>のないことは、なかなか覚えない。",
     "Things I have no interest in are hard to memorize.",
     "흥미가 없는 것은 잘 외워지지 않아요.",
     "沒興趣的事情，總是很難記住。"),
    ("忘れない（わすれない）", "to forget", "잊다", "忘記／唔記得", "2グループ (一段)",
     "<ruby>傘<rt>かさ</rt></ruby>を<ruby>電車<rt>でんしゃ</rt></ruby>に忘れないように<ruby>気<rt>き</rt></ruby>をつける。",
     "I take care not to forget my umbrella on the train.",
     "우산을 전철에 두고 내리지 않도록 조심해요.",
     "小心不要把雨傘忘在電車上。"),
    ("失くさない（なくさない）", "to lose (something)", "잃어버리다", "丟失／弄不見", "1グループ (五段)",
     "<ruby>鍵<rt>かぎ</rt></ruby>を失くさないように、ポケットのファスナーを<ruby>閉<rt>し</rt></ruby>める。",
     "So that I don't lose my keys, I zip up my pocket.",
     "열쇠를 잃어버리지 않도록 주머니 지퍼를 잠가요.",
     "為了不弄丟鑰匙，把口袋拉鍊拉上。"),
    ("払わない（はらわない）", "to pay", "지불하다", "付款／支付", "1グループ (五段)",
     "<ruby>現金<rt>げんきん</rt></ruby>では払わないで、スマホ<ruby>決済<rt>けっさい</rt></ruby>を<ruby>使<rt>つか</rt></ruby>う。",
     "I don't pay with cash, but use smartphone payments.",
     "현금으로 지불하지 않고 스마트폰 결제를 사용해요.",
     "不用現金付款，改用手機行動支付。"),
    ("返さない（かえさない）", "to return (something)", "돌려주다", "歸還／還", "1グループ (五段)",
     "<ruby>借<rt>か</rt></ruby>りた<ruby>本<rt>ほん</rt></ruby>を<ruby>期限<rt>きげん</rt></ruby>までに返さないのはよくない。",
     "It is not good not to return borrowed books by the due date.",
     "빌린 책을 기한까지 돌려주지 않는 것은 좋지 않아요.",
     "借來的書不在期限前歸還是不好的。"),
    ("辞めない（やまない）", "to quit / to stop", "그만두다", "辭職／放棄", "2グループ (一段)",
     "<ruby>大変<rt>たいへん</rt></ruby>だけど、<ruby>夢<rt>ゆめ</rt></ruby>があるからこの<ruby>仕事<rt>しごと</rt></ruby>を辞めない。",
     "It's tough, but I have a dream so I will not quit this job.",
     "힘들지만 꿈이 있어서 이 일을 그만두지 않아요.",
     "雖然辛苦，但因為有夢想，所以我不會辭掉這份工作。")
]

# Section 43: ない-form 5 (22 verbs)
SEC_43_RAW = [
    ("調べない（しらべない）", "to investigate / to check", "조사하다", "查／調查", "2グループ (一段)",
     "インターネットで調べないで、まず<ruby>自分<rt>じぶん</rt></ruby>の<ruby>頭<rt>あたま</rt></ruby>で<ruby>考<rt>かんが</rt></ruby>えてみる。",
     "Without looking it up on the internet, I first try thinking with my own head.",
     "인터넷으로 검색하지 않고 먼저 스스로 생각해 봐요.",
     "不在網路上搜尋，先試著自己動腦思考。"),
    ("修理しない（しゅうりしない）", "to repair", "수리하다", "修理", "3グループ (サ変)",
     "<ruby>古<rt>ふる</rt></ruby>いパソコンは修理しないで、<ruby>新<rt>あたら</rt></ruby>しいものを<ruby>買<rt>か</rt></ruby>う。",
     "Instead of repairing the old computer, I will buy a new one.",
     "오래된 컴퓨터는 수리하지 않고 새것을 사요.",
     "舊電腦不修理了，直接買新的。"),
    ("連絡しない（れんらくしない）", "to contact", "연락하다", "聯絡", "3グループ (サ変)",
     "<ruby>何<rt>なに</rt></ruby>も連絡しないで<ruby>遅刻<rt>ちこく</rt></ruby>するのはよくない。",
     "Being late without contacting at all is bad manners.",
     "아무 연락도 없이 지각하는 것은 좋지 않아요.",
     "什麼都沒聯絡就遲到是很不好的。"),
    ("泊まらない（とまらない）", "to stay overnight", "숙박하다", "過夜／留宿", "1グループ (五段)",
     "<ruby>日帰<rt>ひがえ</rt></ruby>り<ruby>旅行<rt>りょこう</rt></ruby>なので、ホテルには泊まらない。",
     "It's a day trip, so I will not stay overnight at a hotel.",
     "당일치기 여행이라서 호텔에는 묵지 않아요.",
     "因為是當天來回的旅行，所以不住飯店。"),
    ("掃除しない（そうじしない）", "to clean", "청소하다", "打掃／清潔", "3グループ (サ変)",
     "<ruby>週末<rt>しゅうまつ</rt></ruby>まで<ruby>部屋<rt>へや</rt></ruby>を掃除しないと、ゴミがたまってしまう。",
     "If I don't clean the room until the weekend, trash piles up.",
     "주말까지 방을 청소하지 않으면 쓰레기가 쌓여요.",
     "到週末都不打掃房間的話，垃圾會積很多。"),
    ("洗濯しない（せんたくしない）", "to do laundry", "빨래하다", "洗衣服", "3グループ (サ変)",
     "<ruby>雨<rt>あめ</rt></ruby>の<ruby>日<rt>ひ</rt></ruby>は服が<ruby>乾<rt>かわ</rt></ruby>かないので、洗濯しない。",
     "Clothes don't dry on rainy days, so I don't do laundry.",
     "비 오는 날에는 옷이 안 말라서 빨래를 안 해요.",
     "下雨天衣服曬不乾，所以不洗衣服。"),
    ("弾かない（ひかない）", "to play (stringed instrument / piano)", "연주하다", "彈（鋼琴等）", "1グループ (五段)",
     "<ruby>夜遅<rt>よるおそ</rt></ruby>くはピアノを弾かないようにしています。",
     "I make sure not to play the piano late at night.",
     "밤늦게는 피아노를 치지 않도록 조심해요.",
     "深夜盡量不彈鋼琴。"),
    ("歌わない（うたわない）", "to sing", "노래하다", "唱歌", "1グループ (五段)",
     "<ruby>喉<rt>のど</rt></ruby>が<ruby>痛<rt>いた</rt></ruby>いので、カラオケでは歌わないで<ruby>聴<rt>き</rt></ruby>くだけにする。",
     "My throat hurts, so at karaoke I won't sing and will just listen.",
     "목이 아파서 노래방에서는 노래를 안 부르고 듣기만 해요.",
     "喉嚨痛，所以在卡拉OK不唱歌只聽大家唱。"),
    ("集めない（あつめない）", "to collect / to gather", "모으다", "收集／集齊", "2グループ (一段)",
     "これ<ruby>以上<rt>いじょう</rt></ruby>フィギュアを集めないで、<ruby>部屋<rt>へや</rt></ruby>を<ruby>片付<rt>かたづ</rt></ruby>ける。",
     "I won't collect figures any more, and will tidy up my room.",
     "더 이상 피규어를 모으지 않고 방을 정리해요.",
     "不再收集公仔了，把房間整理乾淨。"),
    ("捨てない（すてない）", "to throw away", "버리다", "扔掉／丟棄", "2グループ (一段)",
     "まだ<ruby>使<rt>つか</rt></ruby>えるものは、簡単に捨てないでリサイクルする。",
     "Things that can still be used are not thrown away easily, but recycled.",
     "아직 쓸 수 있는 물건은 쉽게 버리지 않고 재활용해요.",
     "還能用的東西不要輕易扔掉，拿去回收。"),
    ("変えない（かえない）", "to change (something)", "바꾸다", "改變／更換", "2グループ (一段)",
     "<ruby>自分<rt>じぶん</rt></ruby>の<ruby>目標<rt>もくひょう</rt></ruby>は、どんなことがあっても変えない。",
     "Whatever happens, I will not change my goal.",
     "자신의 목표는 어떤 일이 있어도 바꾸지 않아요.",
     "無論發生什麼事，我都不會改變自己的目標。"),
    ("変わらない（かわらない）", "to change (intransitive)", "변하다", "變化／改變", "1グループ (五段)",
     "<ruby>故郷<rt>ふるさと</rt></ruby>の<ruby>景色<rt>けしき</rt></ruby>は、<ruby>昔<rt>むかし</rt></ruby>とちっとも変わらない。",
     "The scenery of my hometown has not changed at all from the past.",
     "고향의 풍경은 예전과 전혀 변하지 않았어요.",
     "故鄉的風景和從前相比一點都沒有改變。"),
    ("運転しない（うんてんしない）", "to drive", "운전하다", "開車／駕駛", "3グループ (サ変)",
     "<ruby>雪<rt>ゆき</rt></ruby>が<ruby>降<rt>ふ</rt></ruby>っている<ruby>日<rt>ひ</rt></ruby>は、<ruby>車<rt>くるま</rt></ruby>を運転しない。",
     "On snowy days, I do not drive a car.",
     "눈이 내리는 날에는 자동차를 운전하지 않아요.",
     "下雪的日子不開車。"),
    ("取らない（とらない）", "to take / to get", "취하다／받다", "取得／獲得", "1グループ (五段)",
     "<ruby>忙<rt>いそが</rt></ruby>しくて、<ruby>今年<rt>ことし</rt></ruby>は<ruby>有給休暇<rt>ゆうきゅうきゅうか</rt></ruby>をあまり取らない。",
     "I'm busy, so I won't take much paid leave this year.",
     "바빠서 올해는 유급휴가를 많이 쓰지 않아요.",
     "因為太忙，今年沒怎麼休特休假。"),
    ("言わない（いわない）", "to say / to tell", "말하다", "說／講", "1グループ (五段)",
     "<ruby>愚痴<rt>ぐち</rt></ruby>を言わないで、<ruby>前向<rt>まえむ</rt></ruby>きに<ruby>頑張<rt>がんば</rt></ruby>ろう。",
     "Let's not complain and do our best positively.",
     "불평을 말하지 말고 긍정적으로 노력하자.",
     "別發牢騷，積極努力吧。"),
    ("気を付けない（きをつけない）", "to pay attention / to be careful", "조심하다", "注意／留心", "2グループ (一段)",
     "<ruby>足元<rt>あしもと</rt></ruby>に気を付けないと、<ruby>転<rt>ころ</rt></ruby>んでしまいますよ。",
     "If you don't watch your step, you will trip and fall.",
     "발밑을 조심하지 않으면 넘어져요.",
     "不注意腳下的話，會跌倒喔。"),
    ("留学しない（りゅうがくしない）", "to study abroad", "유학하다", "留學", "3グループ (サ変)",
     "<ruby>学費<rt>がくひ</rt></ruby>が<ruby>足<rt>た</rt></ruby>りないので、<ruby>今年<rt>ことし</rt></ruby>は留学しないことにした。",
     "Since tuition is insufficient, I decided not to study abroad this year.",
     "학비가 부족해서 올해는 유학하지 않기로 했어요.",
     "學費不夠，所以決定今年不去留學。"),
    ("心配しない（しんぱいしない）", "to worry", "걱정하다", "擔心", "3グループ (サ変)",
     "<ruby>大丈夫<rt>だいじょうぶ</rt></ruby>ですから、何も心配しないでください。",
     "It's all right, so please don't worry about anything.",
     "괜찮으니까 아무것도 걱정하지 마세요.",
     "沒問題的，請什麼都不用擔心。"),
    ("持って行かない（もっていかない）", "to take along (something)", "가져가다", "帶去", "1グループ (五段複合)",
     "<ruby>雨<rt>あめ</rt></ruby>が<ruby>止<rt>や</rt></ruby>んだので、<ruby>傘<rt>かさ</rt></ruby>は持って行かない。",
     "The rain stopped, so I won't take the umbrella with me.",
     "비가 그쳐서 우산은 가지고 가지 않아요.",
     "雨停了，所以不把傘帶出門。"),
    ("持ってこない（もってこない）", "to bring (something)", "가져오다", "帶來", "3グループ (カ変複合)",
     "<ruby>今日<rt>きょう</rt></ruby>は<ruby>教科書<rt>きょうかしょ</rt></ruby>を持ってこないで、タブレットだけ<ruby>持参<rt>じさん</rt></ruby>した。",
     "Today I didn't bring textbooks, only brought my tablet.",
     "오늘은 교과서를 가져오지 않고 태블릿만 지참했어요.",
     "今天沒帶教科書來，只帶了平板。"),
    ("連れて行かない（つれていかない）", "to take someone along", "데려가다", "帶（人）去", "1グループ (五段複合)",
     "<ruby>夜<rt>よる</rt></ruby>の<ruby>映画館<rt>えいがかん</rt></ruby>には、<ruby>小<rt>ちい</rt></ruby>さい<ruby>子供<rt>こども</rt></ruby>を連れて行かない。",
     "I won't take small children along to the movie theater at night.",
     "밤의 영화관에는 어린아이를 데려가지 않아요.",
     "深夜的電影院，不帶小孩一起去。"),
    ("連れてこない（つれてこない）", "to bring someone along", "데려오다", "帶（人）來", "3グループ (カ変複合)",
     "ペットは<ruby>店内<rt>てんない</rt></ruby>に連れてこないでください。",
     "Please do not bring pets inside the store.",
     "반려동물은 매장 안으로 데려오지 마세요.",
     "請勿攜帶寵物進入店內。")
]

# Section 44: 可能形 1 (26 verbs)
SEC_44_RAW = [
    ("行ける・行けます（いける・いけます）", "can go", "갈 수 있다", "能去／可以去", "可能動詞 (1グループ派生)",
     "<ruby>用事<rt>ようじ</rt></ruby>が<ruby>早<rt>はや</rt></ruby>く<ruby>終<rt>お</rt></ruby>わったので、コンサートに行けます！",
     "My errand finished early, so I can go to the concert!",
     "일이 일찍 끝나서 콘서트에 갈 수 있어요!",
     "事情早點辦完了，所以能去演唱會了！"),
    ("帰れる（かえれる）", "can return / go home", "돌아갈 수 있다", "能回去／可以回家", "可能動詞 (1グループ派生)",
     "<ruby>仕事<rt>しごと</rt></ruby>が<ruby>片付<rt>かたづ</rt></ruby>いたので、<ruby>定時<rt>ていじ</rt></ruby>に帰れる。",
     "My work is finished, so I can go home on time.",
     "일이 마무리되어서 정시에 퇴근할 수 있어요.",
     "工作處理完了，可以準時回家。"),
    ("飲める（のめる）", "can drink", "마실 수 있다", "能喝／可以喝", "可能動詞 (1グループ派生)",
     "<ruby>二十歳<rt>はたち</rt></ruby>になったので、お<ruby>酒<rt>さけ</rt></ruby>が飲める。",
     "I turned twenty, so I can drink alcohol.",
     "스무 살이 되어서 술을 마실 수 있어요.",
     "滿二十歲了，可以喝酒了。"),
    ("聞ける（きける）", "can ask / hear", "물을 수 있다", "能問／可以聽", "可能動詞 (1グループ派生)",
     "<ruby>先生<rt>せんせい</rt></ruby>が<ruby>職員室<rt>しょくいんしつ</rt></ruby>にいるので、<ruby>直接<rt>ちょくせつ</rt></ruby><ruby>質問<rt>しつもん</rt></ruby>が聞ける。",
     "The teacher is in the staff room, so I can ask questions directly.",
     "선생님이 교무실에 계셔서 직접 질문을 여쭤볼 수 있어요.",
     "老師在辦公室，所以可以直接詢問問題。"),
    ("聴ける（きける）", "can listen", "들을 수 있다", "能聽／可以欣賞", "可能動詞 (1グループ派生)",
     "サブスクで<ruby>世界中<rt>せかいじゅう</rt></ruby>の<ruby>音楽<rt>おんがく</rt></ruby>がいつでも聴ける。",
     "With streaming, you can listen to music worldwide anytime.",
     "스트리밍으로 전 세계의 음악을 언제든 들을 수 있어요.",
     "透過串流音樂隨時都能收聽全世界的音樂。"),
    ("読める（よめる）", "can read", "읽을 수 있다", "能讀／看得懂", "可能動詞 (1グループ派生)",
     "ふりがながあるので、<ruby>難<rt>むずか</rt></ruby>しい<ruby>漢字<rt>かんじ</rt></ruby>でも読める。",
     "There is furigana, so I can read even difficult kanji.",
     "후리가나가 있어서 어려운 한자도 읽을 수 있어요.",
     "有標假名，所以即使是難漢字也讀得懂。"),
    ("話せる（はなせる）", "can speak", "말할 수 있다", "能說／會講", "可能動詞 (1グループ派生)",
     "<ruby>毎日<rt>まいにち</rt></ruby><ruby>練習<rt>れんしゅう</rt></ruby>して、<ruby>日本語<rt>にほんご</rt></ruby>が<ruby>少<rt>すこ</rt></ruby>し話せるようになった。",
     "Practicing every day, I became able to speak a little Japanese.",
     "매일 연습해서 일본어를 조금 말할 수 있게 되었어요.",
     "每天練習，變得能說一點日語了。"),
    ("会える（あえる）", "can meet", "만날 수 있다", "能見面／可以碰到", "可能動詞 (1グループ派生)",
     "<ruby>明日<rt>あした</rt></ruby>、<ruby>久しぶり<rt>ひさしぶり</rt></ruby>に<ruby>友達<rt>ともだち</rt></ruby>に会えるのが<ruby>楽<rt>たの</rt></ruby>しみです。",
     "I am looking forward to being able to meet my friend tomorrow for the first time in ages.",
     "내일 오랜만에 친구를 만날 수 있어서 기대돼요.",
     "期待明天時隔很久能和朋友見面。"),
    ("買える（かえる）", "can buy", "살 수 있다", "能買／買得到", "可能動詞 (1グループ派生)",
     "ネットで<ruby>限定<rt>げんてい</rt></ruby>のチケットが買えた！",
     "I was able to buy the limited ticket online!",
     "인터넷에서 한정 티켓을 살 수 있었어요!",
     "在網路上買到了限量門票！"),
    ("終われる（おわれる）", "can finish", "끝낼 수 있다", "能結束／可以完成", "可能動詞 (1グループ派生)",
     "みんなで<ruby>協力<rt>きょうりょく</rt></ruby>すれば、<ruby>午前中<rt>ごぜんちゅう</rt></ruby>に終われるはずだ。",
     "If everyone cooperates, we should be able to finish in the morning.",
     "다 함께 협력하면 오전 중에 끝낼 수 있을 거예요.",
     "大家齊心協力，應該能在上午結束。"),
    ("働ける（はたらける）", "can work", "일할 수 있다", "能工作／可以上班", "可能動詞 (1グループ派生)",
     "ビザが<ruby>更新<rt>こうしん</rt></ruby>できたので、<ruby>日本<rt>にほん</rt></ruby>でまだ働ける。",
     "My visa was renewed, so I can still work in Japan.",
     "비자가 갱신되어서 일본에서 계속 일할 수 있어요.",
     "簽證續簽成功了，還可以繼續在日本工作。"),
    ("驚ける（おどろける）", "can be surprised", "놀랄 수 있다", "能感到驚喜", "可能動詞 (1グループ派生)",
     "<ruby>大人<rt>おとな</rt></ruby>になっても<ruby>純粋<rt>じゅんすい</rt></ruby>に驚ける<ruby>心<rt>こころ</rt></ruby>を<ruby>持<rt>も</rt></ruby>っていたい。",
     "Even as an adult, I want to keep a heart that can be purely surprised.",
     "어른이 되어서도 순수하게 놀랄 수 있는 마음을 간직하고 싶어요.",
     "即使長大成人，也希望保有純真驚喜的心。"),
    ("乗れる（のれる）", "can ride / get on", "탈 수 있다", "能搭乘／會騎", "可能動詞 (1グループ派生)",
     "<ruby>練習<rt>れんしゅう</rt></ruby>のおかげで、<ruby>自転車<rt>じてんしゃ</rt></ruby>に乗れるようになった。",
     "Thanks to practice, I became able to ride a bicycle.",
     "연습 덕분에 자전거를 탈 수 있게 되었어요.",
     "多虧了練習，變得會騎腳踏車了。"),
    ("休める（やすめる）", "can rest / take time off", "쉴 수 있다", "能休息／可以放假", "可能動詞 (1グループ派生)",
     "<ruby>来週<rt>らいしゅう</rt></ruby>の<ruby>金曜日<rt>きんようび</rt></ruby>は<ruby>有給<rt>ゆうきゅう</rt></ruby>で休めることになった。",
     "It was decided that I can take paid leave to rest next Friday.",
     "다음 주 금요일은 유급휴가로 쉴 수 있게 되었어요.",
     "下週五可以請有薪假休息了。"),
    ("遊べる（あそべる）", "can hang out / play", "놀 수 있다", "能玩／可以出去玩", "可能動詞 (1グループ派生)",
     "<ruby>宿題<rt>しゅくだい</rt></ruby>を<ruby>全部<rt>ぜんぶ</rt></ruby>やったから、<ruby>心置<rt>こころお</rt></ruby>きなく遊べる。",
     "I finished all my homework, so I can play without worries.",
     "숙제를 다 해서 마음 편히 놀 수 있어요.",
     "作業全部做完了，可以無拘無束地玩了。"),
    ("起きられる（おきられる）", "can wake up", "일어날 수 있다", "起得來／能起床", "可能動詞 (2グループ派生)",
     "<ruby>目覚<rt>めざ</rt></ruby>まし<ruby>時計<rt>どけい</rt></ruby>を２つセットすれば、<ruby>朝<rt>あさ</rt></ruby>６<ruby>時<rt>じ</rt></ruby>に起きられる。",
     "If I set two alarm clocks, I can wake up at 6 a.m.",
     "알람시계를 두 개 맞추면 아침 6시에 일어날 수 있어요.",
     "設兩個鬧鐘的話，早上六點起得來。"),
    ("食べられる（たべられる）", "can eat", "먹을 수 있다", "能吃／吃得下", "可能動詞 (2グループ派生)",
     "<ruby>辛<rt>から</rt></ruby>いものが<ruby>好<rt>す</rt></ruby>きなので、ワサビもたくさん食べられる。",
     "I like spicy food, so I can eat a lot of wasabi too.",
     "매운 것을 좋아해서 와사비도 많이 먹을 수 있어요.",
     "我喜歡吃辣，所以芥末也能吃很多。"),
    ("寝られる（ねられる）", "can sleep", "잘 수 있다", "能睡／睡得著", "可能動詞 (2グループ派生)",
     "<ruby>枕<rt>まくら</rt></ruby>を<ruby>変<rt>か</rt></ruby>えたら、ぐっすり寝られるようになった。",
     "After changing pillows, I can now sleep soundly.",
     "베개를 바꾸었더니 푹 잘 수 있게 되었어요.",
     "換了枕頭之後，能熟睡了。"),
    ("見られる（みられる）", "can see / watch", "볼 수 있다", "能看／看得到", "可能動詞 (2グループ派生)",
     "<ruby>晴<rt>は</rt></ruby>れた<ruby>日<rt>ひ</rt></ruby>には、ここから<ruby>富士山<rt>ふじさん</rt></ruby>が見られる。",
     "On clear days, Mt. Fuji can be seen from here.",
     "맑은 날에는 이곳에서 후지산을 볼 수 있어요.",
     "放晴的日子裡，從這裡能看到富士山。"),
    ("始められる（はじめられる）", "can start (something)", "시작할 수 있다", "能開始", "可能動詞 (2グループ派生)",
     "<ruby>道具<rt>どうぐ</rt></ruby>がすべてそろうと、すぐに<ruby>作業<rt>さぎょう</rt></ruby>を始められる。",
     "Once all tools are ready, we can start work immediately.",
     "도구가 다 갖춰지면 곧바로 작업을 시작할 수 있어요.",
     "工具齊全後，就能馬上開始作業。"),
    ("忘れられる（わすれられる）", "can forget", "잊을 수 있다", "能忘記", "可能動詞 (2グループ派生)",
     "<ruby>楽<rt>たの</rt></ruby>しい<ruby>時間<rt>じかん</rt></ruby>をすごして、<ruby>嫌<rt>いや</rt></ruby>なことを忘れられた。",
     "Spending enjoyable time, I was able to forget unpleasant things.",
     "즐거운 시간을 보내며 안 좋은 일을 잊을 수 있었어요.",
     "度過了愉快的時光，能把不愉快的事都忘了。"),
    ("覚えられる（おぼえられる）", "can memorize / remember", "외울 수 있다", "能記住／背得起", "可能動詞 (2グループ派生)",
     "カードを<ruby>使<rt>つか</rt></ruby>うと、<ruby>新<rt>あたら</rt></ruby>しい<ruby>単語<rt>たんご</rt></ruby>がすぐに覚えられる。",
     "Using cards, I can memorize new words quickly.",
     "단어 카드를 사용하면 새로운 단어를 금방 외울 수 있어요.",
     "使用字卡的話，新單字很快就能記住。"),
    ("降りられる（おりられる）", "can get off", "내릴 수 있다", "能下車", "可能動詞 (2グループ派生)",
     "<ruby>人<rt>ひと</rt></ruby>が<ruby>多<rt>おお</rt></ruby>かったけれど、なんとか<ruby>駅<rt>えき</rt></ruby>で降りられた。",
     "There were many people, but somehow I was able to get off at the station.",
     "사람이 많았지만 어찌어찌 역에서 내릴 수 있었어요.",
     "雖然人很多，但總算順利在車站下車了。"),
    ("来られる（こられる）", "can come", "올 수 있다", "能來／可以過來", "可能動詞 (カ変派生)",
     "<ruby>都合<rt>つごう</rt></ruby>がよければ、<ruby>明日<rt>あした</rt></ruby>のパーティーに来られますか？",
     "If it is convenient for you, can you come to tomorrow's party?",
     "형편이 괜찮으시면 내일 파티에 오실 수 있나요?",
     "如果方便的話，明天能來派對嗎？"),
    ("できる・できます", "can do / be ready", "할 수 있다", "會／可以／能做", "可能動詞 (する可能形)",
     "<ruby>努力<rt>どりょく</rt></ruby>したおかげで、<ruby>難<rt>むずか</rt></ruby>しい<ruby>料理<rt>りょうり</rt></ruby>も作ることができます。",
     "Thanks to my efforts, I can make difficult dishes too.",
     "노력한 덕분에 어려운 요리도 만들 수 있어요.",
     "多虧了努力，連難做的料理我也能做出來了。"),
    ("勉強できる（べんきょうできる）", "can study", "공부할 수 있다", "能學習／可以讀書", "可能動詞 (サ変可能形)",
     "<ruby>静<rt>しず</rt></ruby>かなカフェで、<ruby>集中<rt>しゅうちゅう</rt></ruby>して勉強できる。",
     "At a quiet cafe, I can study with focus.",
     "조용한 카페에서 집중해서 공부할 수 있어요.",
     "在安靜的咖啡廳裡，可以專心讀書。")
]

# Section 45: 可能形 2 (24 verbs)
SEC_45_RAW = [
    ("入れる・入れます（いれる・いれます）", "can enter / can go in", "들어갈 수 있다", "能進去／可以進入", "可能動詞 (1グループ入るの可能形)",
     "<ruby>予約<rt>よやく</rt></ruby>なしでも、このレストランに入れますか？",
     "Even without a reservation, can we enter this restaurant?",
     "예약 없이도 이 레스토랑에 들어갈 수 있나요?",
     "即使沒有預約，也能進去這間餐廳嗎？"),
    ("着ける（つける）", "can arrive", "도착할 수 있다", "能抵達／可以到達", "可能動詞 (1グループ着くの可能形)",
     "<ruby>渋滞<rt>じゅうたい</rt></ruby>がなければ、<ruby>予定<rt>よてい</rt></ruby>どおりの<ruby>時間<rt>じかん</rt></ruby>に着けるはずです。",
     "If there is no traffic jam, we should be able to arrive as scheduled.",
     "교통체증이 없으면 예정대로 도착할 수 있을 거예요.",
     "如果不塞車的話，應該能按預定時間到達。"),
    ("渡れる（わたれる）", "can cross", "건널 수 있다", "能過（馬路）", "可能動詞 (1グループ渡るの可能形)",
     "<ruby>信号<rt>しんごう</rt></ruby>が<ruby>青<rt>あお</rt></ruby>になったので、<ruby>安全<rt>あんぜん</rt></ruby>に<ruby>道<rt>みち</rt></ruby>を渡れる。",
     "The light turned green, so we can cross the street safely.",
     "신호가 파란불이 되어서 안전하게 길을 건널 수 있어요.",
     "信號燈變綠燈了，可以安全地過馬路。"),
    ("歩ける（あるける）", "can walk", "걸을 수 있다", "能走／走得動", "可能動詞 (1グループ歩くの可能形)",
     "<ruby>足<rt>あし</rt></ruby>の<ruby>怪我<rt>けが</rt></ruby>が<ruby>治<rt>なお</rt></ruby>って、また<ruby>普通<rt>ふつう</rt></ruby>に歩けるようになった。",
     "My foot injury healed, so I can walk normally again.",
     "다리 부상이 나아서 다시 평소처럼 걸을 수 있게 되었어요.",
     "腳傷痊癒了，又能夠像平時一樣行走了。"),
    ("走れる（はしれる）", "can run", "달릴 수 있다", "能跑／跑得動", "可能動詞 (1グループ走るの可能形)",
     "<ruby>体力<rt>たいりょく</rt></ruby>がついて、５キロも休まずに走れる。",
     "My stamina increased, and I can run 5 kilometers without resting.",
     "체력이 붙어서 5킬로미터도 쉬지 않고 달릴 수 있어요.",
     "體力變好了，不休息也能跑完五公里。"),
    ("起こせる（おこせる）", "can wake someone up", "깨울 수 있다", "能叫醒（某人）", "可能動詞 (1グループ起こすの可能形)",
     "<ruby>明日<rt>あした</rt></ruby>の<ruby>朝<rt>あさ</rt></ruby>は<ruby>私<rt>わたし</rt></ruby>が<ruby>早<rt>はや</rt></ruby>く<ruby>起<rt>お</rt></ruby>きて、あなたを起こせるよ。",
     "Tomorrow morning I will get up early and can wake you up.",
     "내일 아침은 내가 일찍 일어나서 너를 깨워 줄 수 있어.",
     "明天早上我會早起，可以叫你起床喔。"),
    ("洗える（あらえる）", "can wash", "빨 수 있다", "可以水洗／能洗", "可能動詞 (1グループ洗うの可能形)",
     "このスーツは<ruby>自宅<rt>じたく</rt></ruby>の<ruby>洗濯機<rt>せんたくき</rt></ruby>で<ruby>丸洗<rt>まるあら</rt></ruby>いできる。",
     "This suit can be fully washed in home washing machines.",
     "이 정장은 집 세탁기에서 물세탁할 수 있어요.",
     "這套西裝可以在家裡的洗衣機水洗。"),
    ("脱げる（ぬげる）", "can take off (clothes) / come off", "벗을 수 있다", "能脫下", "可能動詞 (1グループ脱ぐの可能形)",
     "<ruby>暑<rt>あつ</rt></ruby>くなったら、すぐに上着が脱げる。",
     "If it gets hot, I can immediately take off my jacket.",
     "더워지면 곧바로 겉옷을 벗을 수 있어요.",
     "要是變熱了，隨時可以把外套脫下來。"),
    ("使える（つかえる）", "can use", "쓸 수 있다", "能使用／可以使用", "可能動詞 (1グループ使うの可能形)",
     "このカードは<ruby>世界中<rt>せかいじゅう</rt></ruby>のどこでも使える。",
     "This card can be used anywhere around the world.",
     "이 카드는 전 세계 어디에서나 쓸 수 있어요.",
     "這張卡在世界各地都能使用。"),
    ("作れる（つくれる）", "can make", "만들 수 있다", "能做／會製作", "可能動詞 (1グループ作るの可能形)",
     "<ruby>母<rt>はは</rt></ruby>に<ruby>教<rt>おし</rt></ruby>わって、おいしいカレーが作れるようになった。",
     "Taught by my mother, I became able to make delicious curry.",
     "어머니께 배워서 맛있는 카레를 만들 수 있게 되었어요.",
     "跟媽媽學過之後，變得能做出美味的咖哩了。"),
    ("切れる（きれる）", "can cut / is sharp", "자를 수 있다", "能切／鋒利", "可能動詞 (1グループ切るの可能形)",
     "この<ruby>包丁<rt>ほうちょう</rt></ruby>はよく切れるので、<ruby>料理<rt>りょうり</rt></ruby>が<ruby>楽<rt>たの</rt></ruby>しい。",
     "This kitchen knife cuts very well, so cooking is fun.",
     "이 식칼은 잘 들어서 요리가 즐거워요.",
     "這把菜刀切得很俐落，做菜真開心。"),
    ("書ける（かける）", "can write", "쓸 수 있다", "能寫／會寫", "可能動詞 (1グループ書くの可能形)",
     "<ruby>練習<rt>れんしゅう</rt></ruby>したら、<ruby>自分<rt>じぶん</rt></ruby>の<ruby>名前<rt>なまえ</rt></ruby>が<ruby>漢字<rt>かんじ</rt></ruby>で書けるようになった。",
     "After practicing, I became able to write my name in kanji.",
     "연습했더니 내 이름을 한자로 쓸 수 있게 되었어요.",
     "練習之後，變得能用漢字寫自己的名字了。"),
    ("待てる（まてる）", "can wait", "기다릴 수 있다", "能等／等得了", "可能動詞 (1グループ待つの可能形)",
     "<ruby>本<rt>ほん</rt></ruby>を<ruby>読<rt>よ</rt></ruby>んでいるので、３０<ruby>分<rt>ぷん</rt></ruby>くらいなら待てるよ。",
     "I am reading a book, so I can wait about 30 minutes.",
     "책을 읽고 있어서 30분 정도라면 기다릴 수 있어.",
     "我正在看書，三十分鐘左右的話我能等喔。"),
    ("思える（おもえる）", "can think / seem like", "생각될 수 있다", "覺得／似乎", "可能動詞 (1グループ思うの可能形)",
     "彼の提案はとても現実的に思える。",
     "His proposal seems very realistic to me.",
     "그의 제안은 매우 현실적으로 느껴져요.",
     "他的提案讓人覺得非常切合實際。"),
    ("知れる（しれる）", "can be known / find out", "알려지다", "能知道／得以知曉", "可能動詞 (1グループ知るの可能形)",
     "インターネットのおかげで、<ruby>最新<rt>さいしん</rt></ruby>の<ruby>情報<rt>じょうほう</rt></ruby>がすぐに知れる。",
     "Thanks to the internet, the latest information can be known right away.",
     "인터넷 덕분에 최신 정보를 바로 알 수 있어요.",
     "多虧了網路，能立刻得知最新的資訊。"),
    ("出られる（でられる）", "can go out / attend", "나갈 수 있다", "能出去／能出席", "可能動詞 (2グループ出るの可能形)",
     "<ruby>体調<rt>たいちょう</rt></ruby>が<ruby>良<rt>よ</rt></ruby>くなったので、<ruby>明日<rt>あした</rt></ruby>の<ruby>試合<rt>しあい</rt></ruby>に出られる。",
     "My physical condition improved, so I can participate in tomorrow's match.",
     "몸 상태가 좋아져서 내일 시합에 나갈 수 있어요.",
     "身體恢復了，所以能參加明天的比賽。"),
    ("着られる（きられる）", "can wear (top)", "입을 수 있다", "穿得下／能穿", "可能動詞 (2グループ着るの可能形)",
     "<ruby>痩<rt>や</rt></ruby>せたので、お<ruby>気<rt>き</rt></ruby>に<ruby>入<rt>い</rt></ruby>りのドレスがまた着られる。",
     "I lost weight, so I can wear my favorite dress again.",
     "살이 빠져서 마음에 드는 드레스를 다시 입을 수 있어요.",
     "瘦下來了，又穿得下心愛的洋裝了。"),
    ("開けられる（あけられる）", "can open", "열 수 있다", "能打開", "可能動詞 (2グループ開けるの可能形)",
     "ジャムのフタが<ruby>固<rt>かた</rt></ruby>かったが、タオルを<ruby>使<rt>つか</rt></ruby>って開けられた。",
     "The jam lid was tight, but using a towel I was able to open it.",
     "잼 뚜껑이 뻑뻑했지만 수건을 써서 열 수 있었어요.",
     "果醬蓋很緊，但用了毛巾就能打開了。"),
    ("閉められる（しめられる）", "can close", "닫을 수 있다", "能關上", "可能動詞 (2グループ閉めるの可能形)",
     "カーテンを閉められるので、<ruby>日差<rt>ひざ</rt></ruby>しが<ruby>強<rt>つよ</rt></ruby>くても<ruby>平気<rt>へいき</rt></ruby>です。",
     "I can close the curtain, so even if the sunlight is strong it's fine.",
     "커튼을 닫을 수 있어서 햇빛이 강해도 괜찮아요.",
     "可以拉上窗簾，所以就算陽光強烈也沒關係。"),
    ("答えられる（こたえられる）", "can answer", "대답할 수 있다", "能回答", "可能動詞 (2グループ答えるの可能形)",
     "<ruby>復習<rt>ふくしゅう</rt></ruby>していたので、<ruby>先生<rt>せんせい</rt></ruby>の<ruby>質問<rt>しつもん</rt></ruby>にしっかり答えられた。",
     "Because I reviewed, I was able to answer the teacher's question firmly.",
     "복습을 해 두어서 선생님 질문에 똑똑히 대답할 수 있었어요.",
     "因為有複習，所以能確實回答老師的問題。"),
    ("教えられる（おしえられる）", "can teach / tell", "가르쳐 줄 수 있다", "能教／可以告訴", "可能動詞 (2グループ教えるの可能形)",
     "<ruby>道<rt>みち</rt></ruby>をよく<ruby>知<rt>し</rt></ruby>っているから、<ruby>駅<rt>えき</rt></ruby>までの<ruby>行<rt>い</rt></ruby>き<ruby>方<rt>かた</rt></ruby>を教えられるよ。",
     "I know the way well, so I can tell you how to get to the station.",
     "길을 잘 알고 있으니까 역까지 가는 방법을 가르쳐 줄 수 있어.",
     "我很熟悉這條路，所以可以告訴你怎麼走到車站喔。"),
    ("聞こえる（きこえる）", "can hear / audible", "들리다", "聽得見／聽得到", "可能・自発動詞",
     "<ruby>窓<rt>まど</rt></ruby>の<ruby>外<rt>そと</rt></ruby>から<ruby>鳥<rt>とり</rt></ruby>の<ruby>鳴<rt>な</rt></ruby>き<ruby>声<rt>ごえ</rt></ruby>が聞こえる。",
     "I can hear birds chirping from outside the window.",
     "창밖에서 새들의 지저귀는 소리가 들려요.",
     "窗外傳來了小鳥的鳴叫聲。"),
    ("見える（みえる）", "can see / visible", "보이다", "看得見／看得到", "可能・自発動詞",
     "<ruby>屋上<rt>おくじょう</rt></ruby>からは<ruby>海<rt>うみ</rt></ruby>がきれいに見える。",
     "From the rooftop, the sea can be seen beautifully.",
     "옥상에서는 바다가 아름답게 보여요.",
     "從頂樓可以美麗地看見大海。"),
    ("わかる・わかります", "can understand / know", "이해할 수 있다", "明白／理解／懂", "状態動詞 (わかる自体に可能の意味)",
     "<ruby>説明<rt>せつめい</rt></ruby>を<ruby>丁寧<rt>ていねい</rt></ruby>に<ruby>聞<rt>き</rt></ruby>いたので、やり<ruby>方<rt>かた</rt></ruby>がよくわかりました。",
     "Listening carefully to the explanation, I understood the method well.",
     "설명을 꼼꼼히 들어서 하는 방법을 잘 알 수 있었어요.",
     "仔細聽了說明之後，很清楚明白了做法。")
]
